### PR TITLE
Add firmware_update phase

### PR DESCRIPTION
**Pull request by nancyc12**
## Description

Base on [CR033 - Firmware updates for regression testing](https://docs.google.com/document/d/1yMYK5IUFyhb8Y5-pbxOjBekvRkasbUjee7Nw1ySkA5g), introduce a new optional phase **firmware_update** after provision phase to handle request for firmware update on the device. As in the spec, this new phase is implemented in `DefaultDevice`, so it won't need any change on existing `DeviceConnector` codes.

To trigger **firmware_update** phase, the following section needs to be provided in job.yaml. If the `firmware_update_data` section is missing from the job, this phase will not run. 
```
firmware_update_data:
  version: < latest >
  ignore_failure: < false | true >
```
Variables in `firmware_update_data`:
- `version`: The desired firmware level on the device. Currently it only supports `latest` (upgrading all components in the device with the latest firmware release). More options are planned to be implemented in the future once we gathering data for working firmware baseline on devices.
- `ignore_failure`: When set to `false`, **Testflinger Agent** will suspend the job if **firmware_update** phase return a status other than 0, which implies there's a failure during firmware_update phase. If set to `true`, the job will continue regardless the status of **firmware_update** phase.

### Code changes
Update schema.py to let testflinger server accept job with `firmware_update_data` section. 
Update job_detail.html to let it display **firmware_update** phase information.

In order to make it work as a whole, there're also PR raised in [testflinger-agent](https://github.com/canonical/testflinger-agent/pull/40) and [snappy-device-agents](https://github.com/canonical/snappy-device-agents/pull/91).

## Resolved issues

 N/A
## Documentation

As discussed with @tang-mm, the documentation for **firmware_update** phase should include the following:

- [x] **General Introduction**: 
covered in #134

- [x] **Testflinger agents config**: 
definition and usage for `firmware_update_command`, which has been updated in #113

- [x] **Testflinger jobs config**: 
covered in #134

- [ ] **Troubleshooting**: 
working on adding more detail in https://github.com/canonical/snappy-device-agents/pull/91 (e.g., what's the meaning of error messages and where can users find debug log), and as others, the documentation is expected to landed here in docs/ folder to be on readthedocs site.

## Tests

It's tested by building a dev testflinger server with [docker](https://github.com/canonical/testflinger/blob/main/HACKING.md#docker) along with modified [testflinger-agent](https://github.com/canonical/testflinger-agent/pull/40) and snappy-device-agents.

- [x] Unit tests with tox
```
u@u:~/testflinger/testflinger$ tox
py installed: APIFlask==2.0.2,apispec==6.3.0,astroid==3.0.0,async-timeout==4.0.3,black==23.9.1,blinker==1.6.3,certifi==2023.7.22,click==8.1.7,coverage==7.3.2,dill==0.3.7,dnspython==2.4.2,exceptiongroup==1.1.3,flake8==6.1.0,flask==3.0.0,Flask-HTTPAuth==4.8.0,flask-marshmallow==0.15.0,Flask-PyMongo==2.3.0,gevent==23.9.1,greenlet==3.0.0,gunicorn==21.2.0,importlib-metadata==6.8.0,iniconfig==2.0.0,isort==5.12.0,itsdangerous==2.1.2,Jinja2==3.1.2,MarkupSafe==2.1.3,marshmallow==3.20.1,mccabe==0.7.0,mock==5.1.0,mongomock==4.1.2,mypy-extensions==1.0.0,ops==2.7.0,packaging==23.2,pathspec==0.11.2,platformdirs==3.11.0,pluggy==1.3.0,prometheus-client==0.17.1,pycodestyle==2.11.1,pyflakes==3.1.0,pylint==3.0.1,pymongo==4.5.0,pytest==7.4.2,pytest-cov==4.1.0,pytest-mock==3.11.1,PyYAML==6.0.1,redis==5.0.1,sentinels==1.0.0,sentry-sdk==1.32.0,-e git+git@github.com:canonical/testflinger.git@55cb7c3b105b7699ab375c3f03e9d5d81df0a590#egg=testflinger,tomli==2.0.1,tomlkit==0.12.1,typing-extensions==4.8.0,urllib3==2.0.6,webargs==8.3.0,websocket-client==1.6.4,werkzeug==3.0.0,zipp==3.17.0,zope.event==5.0,zope.interface==6.1
py run-test-pre: PYTHONHASHSEED='3187804300'
py run-test-pre: commands[0] | /home/u/testflinger/testflinger/.tox/py/bin/pip install -e .
Obtaining file:///home/u/testflinger/testflinger
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: prometheus-client in ./.tox/py/lib/python3.8/site-packages (from testflinger==1.1.0) (0.17.1)
Requirement already satisfied: gunicorn in ./.tox/py/lib/python3.8/site-packages (from testflinger==1.1.0) (21.2.0)
Requirement already satisfied: gevent in ./.tox/py/lib/python3.8/site-packages (from testflinger==1.1.0) (23.9.1)
Requirement already satisfied: flask-pymongo in ./.tox/py/lib/python3.8/site-packages (from testflinger==1.1.0) (2.3.0)
Requirement already satisfied: apiflask in ./.tox/py/lib/python3.8/site-packages (from testflinger==1.1.0) (2.0.2)
Requirement already satisfied: pyyaml in ./.tox/py/lib/python3.8/site-packages (from testflinger==1.1.0) (6.0.1)
Requirement already satisfied: sentry-sdk[flask] in ./.tox/py/lib/python3.8/site-packages (from testflinger==1.1.0) (1.32.0)
Requirement already satisfied: flask in ./.tox/py/lib/python3.8/site-packages (from testflinger==1.1.0) (3.0.0)
Requirement already satisfied: redis in ./.tox/py/lib/python3.8/site-packages (from testflinger==1.1.0) (5.0.1)
Requirement already satisfied: packaging in ./.tox/py/lib/python3.8/site-packages (from gunicorn->testflinger==1.1.0) (23.2)
Requirement already satisfied: zope.event in ./.tox/py/lib/python3.8/site-packages (from gevent->testflinger==1.1.0) (5.0)
Requirement already satisfied: greenlet>=2.0.0; platform_python_implementation == "CPython" and python_version < "3.11" in ./.tox/py/lib/python3.8/site-packages (from gevent->testflinger==1.1.0) (3.0.0)
Requirement already satisfied: zope.interface in ./.tox/py/lib/python3.8/site-packages (from gevent->testflinger==1.1.0) (6.1)
Requirement already satisfied: PyMongo>=3.3 in ./.tox/py/lib/python3.8/site-packages (from flask-pymongo->testflinger==1.1.0) (4.5.0)
Requirement already satisfied: webargs>=8.3 in ./.tox/py/lib/python3.8/site-packages (from apiflask->testflinger==1.1.0) (8.3.0)
Requirement already satisfied: flask-marshmallow>=0.12.0 in ./.tox/py/lib/python3.8/site-packages (from apiflask->testflinger==1.1.0) (0.15.0)
Requirement already satisfied: apispec>=6 in ./.tox/py/lib/python3.8/site-packages (from apiflask->testflinger==1.1.0) (6.3.0)
Requirement already satisfied: flask-httpauth>=4 in ./.tox/py/lib/python3.8/site-packages (from apiflask->testflinger==1.1.0) (4.8.0)
Requirement already satisfied: urllib3>=1.26.11; python_version >= "3.6" in ./.tox/py/lib/python3.8/site-packages (from sentry-sdk[flask]->testflinger==1.1.0) (2.0.6)
Requirement already satisfied: certifi in ./.tox/py/lib/python3.8/site-packages (from sentry-sdk[flask]->testflinger==1.1.0) (2023.7.22)
Requirement already satisfied: markupsafe; extra == "flask" in ./.tox/py/lib/python3.8/site-packages (from sentry-sdk[flask]->testflinger==1.1.0) (2.1.3)
Requirement already satisfied: blinker>=1.1; extra == "flask" in ./.tox/py/lib/python3.8/site-packages (from sentry-sdk[flask]->testflinger==1.1.0) (1.6.3)
Requirement already satisfied: importlib-metadata>=3.6.0; python_version < "3.10" in ./.tox/py/lib/python3.8/site-packages (from flask->testflinger==1.1.0) (6.8.0)
Requirement already satisfied: itsdangerous>=2.1.2 in ./.tox/py/lib/python3.8/site-packages (from flask->testflinger==1.1.0) (2.1.2)
Requirement already satisfied: Jinja2>=3.1.2 in ./.tox/py/lib/python3.8/site-packages (from flask->testflinger==1.1.0) (3.1.2)
Requirement already satisfied: click>=8.1.3 in ./.tox/py/lib/python3.8/site-packages (from flask->testflinger==1.1.0) (8.1.7)
Requirement already satisfied: Werkzeug>=3.0.0 in ./.tox/py/lib/python3.8/site-packages (from flask->testflinger==1.1.0) (3.0.0)
Requirement already satisfied: async-timeout>=4.0.2; python_full_version <= "3.11.2" in ./.tox/py/lib/python3.8/site-packages (from redis->testflinger==1.1.0) (4.0.3)
Requirement already satisfied: setuptools in ./.tox/py/lib/python3.8/site-packages (from zope.event->gevent->testflinger==1.1.0) (44.0.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in ./.tox/py/lib/python3.8/site-packages (from PyMongo>=3.3->flask-pymongo->testflinger==1.1.0) (2.4.2)
Requirement already satisfied: marshmallow>=3.0.0 in ./.tox/py/lib/python3.8/site-packages (from webargs>=8.3->apiflask->testflinger==1.1.0) (3.20.1)
Requirement already satisfied: zipp>=0.5 in ./.tox/py/lib/python3.8/site-packages (from importlib-metadata>=3.6.0; python_version < "3.10"->flask->testflinger==1.1.0) (3.17.0)
Installing collected packages: testflinger
  Attempting uninstall: testflinger
    Found existing installation: testflinger 1.1.0
    Uninstalling testflinger-1.1.0:
      Successfully uninstalled testflinger-1.1.0
  Running setup.py develop for testflinger
Successfully installed testflinger
_________________________________________ summary _________________________________________
  py: commands succeeded
  congratulations :)
```
- [x] Testflinger server is able to accept job.yaml with `firmware_update_data` section
- [x] Testflinger webpage is able to display `firmware_update_data`, `firmware_update_status` and `firmware_update_output` section

### CODE REVIEW

**Review by jocave — CHANGES_REQUESTED** [review]
Please add to the PR some documentation describing the phase and how to use it

**Comment by nancyc12** [comment]
Sorry for the poor description. Updated it!

**Comment by plars** [comment]
> What I would really like is for us from now to always land the documentation in the place we want it to end up. So the changes that are currently going in to a README here: https://github.com/canonical/testflinger-agent/tree/add_firmware_update_phase#test-phases should end up in the docs/ folder here - I would ask @tang-mm exactly where, maybe an explanation doc titled "Test Phases"

@jocave I think Nancy already did this in https://github.com/canonical/testflinger-agent/pull/40/files - which is the associated branch with the changes for testflinger-agent. The PR here just makes it possible to submit a job with this data, but none of it is usable with the other pieces.

**Review by plars — APPROVED** [review]
I'm ok with it in this state, but please make sure Jonathan is in agreement before landing. I have some pieces in progress to advance the monorepo and once we do, the changes you added in https://github.com/canonical/testflinger-agent/pull/40/files will be in the same repo with this, and linkable more easily from docs in this repo.

**Comment by beliaev-maksim** [comment]
+1

**Review by jocave — CHANGES_REQUESTED** [review]
Nope, it's not what I asked for. I want documentation of the new phase to land such that it is available on the readthedocs site (in Diátaxis format) hence in the docs/ folder of this repo.

**Comment by nancyc12** [comment]
Updated documentation section above to summarize the discussion with @tang-mm . 
@jocave are we anticipate to have all documentation filed to make this PR eligible for merging?

**Comment by nancyc12** [comment]
Move the changes to #141.

**Pull request closed without merging**
