### PR TITLE
Update README with the current configuration options

### LINKED ISSUE #23: Update README with info about MongoDB
Please, fix the information about [configuration values in README](https://github.com/canonical/testflinger#configuration), since we don't use Redis anymore.

### PR DESCRIPTION
**Pull request by plars**
fixes #23

### CODE REVIEW

**Review by nadzyah — CHANGES_REQUESTED** [review]
[This section](https://github.com/canonical/testflinger/blob/b8aea2f90341e901c9fade6597566a38fa42b03b/README.rst#installation) also should be updated:

"Before installing testflinger, you will need to have a **redis** server available somewhere. By default, testflinger will try to attach to one on localhost, but if you prefer, you can configure it to use a **redis** server on another server.”

**Comment by plars** [comment]
Good catch, thanks!

**Review by nadzyah — APPROVED** [review]
Lgtm

**Comment by plars** [comment]
Let's not merge this until we sort out all the questions on the other pull request, since this could be completely invalid depending on the outcome of the other one.

**Comment by nadzyah** [comment]
@plars could you, please, update or merge this PR, since #22 is merged?

**Pull request merged**
