### PR TITLE
Fix sdwire detection issue

### PR DESCRIPTION
**Pull request by nancyc12**
## Description
This is an enhancement patch for https://github.com/canonical/testflinger/pull/238.
We have deployed this change on agents for RPIs machines for weeks and it seems to ease the sdwire detection issue as we power cycling NanoPi and DUT back to back.

## Tests
Have deployed them in real agents and run for weeks.

### CODE REVIEW

**Review by kevinyehk — DISMISSED** [review]
LGTM +1

**Review by jocave — COMMENTED** [review]
I am pleased that testing seems to indicate this makes the setup more reliable, however it's not clear to me from looking at the code whether this guarantees that the control host and the DUT are off at the same time (something that I think we wanted to achieve to make sure the sdwire resets). The code seems to run through all the commands of the control host reboot script and then does the hardreset - could the control host be back on before the hard reset happens?

**Review by plars — DISMISSED** [review]
Nice, it has definitely seemed a lot more stable over the last week or so. It will be good to get this rolled out to the devices. Thanks!

**Comment by nancyc12** [comment]
@jocave We started with making the control host and the DUT off at the same time, but then we saw some cases that were not 100% fixing the sdwire issue. Have tried different power cycle orders and end up with this one as it is most stable.

**Comment by jocave** [comment]
> @jocave We started with making the control host and the DUT off at the same time, but then we saw some cases that were not 100% fixing the sdwire issue. Have tried different power cycle orders and end up with this one as it is most stable.

Ok, thanks for the explanation

**Review by plars — APPROVED** [review]
Thanks for the rebase, +1

**Pull request merged**
