### PR TITLE
Fix command typo in README

### PR DESCRIPTION
**Pull request by Cypresslin**

### CODE REVIEW

**Review by plars — CHANGES_REQUESTED** [review]
Actually, if we are going to change this, we should probably recommend that they use `pip install .` instead

**Comment by Cypresslin** [comment]
Hi Paul,

I am not sure how should I modify this base on your comment.
Please feel free to close this PR.

Thanks
Sam

**Comment by nadzyah** [comment]
> Hi Paul,
> 
> I am not sure how should I modify this base on your comment. Please feel free to close this PR.
> 
> Thanks Sam

@Cypresslin Just replace `./setup.py install` with `pip install .`

**Comment by Cypresslin** [comment]
Hi @nadzyah,
thanks for the info, I have this install command along with some instruction description updated.

**Review by nadzyah — APPROVED** [review]
lgtm

**Review by plars — APPROVED** [review]

**Pull request merged**
